apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: ${name}
spec:
  replicas: 1
  env:
 
  build:
    source:
      ddl: |
        CREATE DATABASE {name} OPTIONS (ANNOTATION 'provide your description here..');
        USE DATABASE {name};

        CREATE VIRTUAL SCHEMA {name};
        SET SCHEMA {name};

        CREATE VIEW SAMPLE AS SELECT 1 as valid;
