apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: $!DUMMY!$
spec:
  replicas: 1
  env:
 
  build:
    source:
      ddl: |
        CREATE DATABASE $!DUMMY!$ OPTIONS (ANNOTATION 'provide your description here..');
        USE DATABASE $!DUMMY!$;

        CREATE VIRTUAL SCHEMA $!DUMMY!$;
        SET SCHEMA $!DUMMY!$;

        CREATE VIEW SAMPLE AS SELECT 1 as valid;
