apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: example
spec:
  replicas: 1
  env:
    - name: myvar
      value: test
  datasources:
    - name: mariadb
      type: mysql
      properties:
        - name: user
          value: Paolo
        - name: password
          valueFrom:
            secretKeyRef:
              name: sample-ds
              key: passwd
        - name: email
          valueFrom:
            configMapKeyRef:
              name: sample-ds
              key: mail
  build:
    source:
      ddl: >
        CREATE DATABASE example OPTIONS (ANNOTATION 'provide your description
        here..');
        USE DATABASE example;
        CREATE VIRTUAL SCHEMA example;
        SET SCHEMA example;
        CREATE VIEW SAMPLE AS SELECT 1 as valid;
