apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: example
spec:
  replicas: 1
  env:
    - name: SPRING_TEIID_DATA_MONGODB_MYPERSONALMONGODB_REMOTE_SERVER_LIST
      value: ""
    - name: SPRING_TEIID_DATA_MONGODB_MYPERSONALMONGODB_USER
      value: Paolo
    - name: SPRING_TEIID_DATA_MONGODB_MYPERSONALMONGODB_PASSWORD
      value: ""
    - name: SPRING_TEIID_DATA_MONGODB_MYPERSONALMONGODB_DATABASE
      value: ""
    - name: SPRING_TEIID_DATA_MONGODB_MYPERSONALMONGODB_AUTH_DATABASE
      value: ""
    - name: SPRING_TEIID_DATA_MONGODB_MYPERSONALMONGODB_SSL
      value: ""
  build:
    source:
      ddl: >
        CREATE DATABASE example OPTIONS (ANNOTATION 'provide your description
        here..');
        USE DATABASE example;
        CREATE VIRTUAL SCHEMA example;
        SET SCHEMA example;
        CREATE VIEW SAMPLE AS SELECT 1 as valid;
